### ISSUE TITLE
Installation Fails on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by astoklas** [bheisig/i-doit-scripts#1]
I tried to install the open i-doit on a fresh Ubuntu. 
When the installer comes to downloading the i-doit it fails with "Unable to download installation file"
It seems that the parsing for the URL and latest version fails as it prints out:
Found i-doit open <title>i-doit (released on <revision>21901</revision>) and the parameters for wget are:
$file /tmp/i-doit_2017-m-d/i-doit.zip 
$url <release>2017-06-26</release>

**Comment by bheisig** [comment]
Hi @astoklas,
Thanks for your report. As you can see I committed a patch. Can you please give it a try?
Benjamin
