### ISSUE TITLE
idoit-install.sh fails on Ubuntu

### ISSUE THREAD

**Issue by GordonFreemem** [bheisig/i-doit-scripts#2]
The install script fails to detect a fresh install of ubuntu 16.04 (xenial). 

identifyOS first searches for /etc/debian_version and if it contains "strech/sid" it aborts. But on ubuntu (at least 16.04) this is the case. So the function doesn't even test for the ubuntu specific lsb_release output and fails.

**Comment by bheisig** [comment]
Hi Gordon,

Thanks for your report. I can confirm that this is a reproducible bug. It has been fixed in last commit. Please try again.

Greetings,
Benjamin
