### ISSUE TITLE
idoit-install.sh doesn't work properly behing proxy

### ISSUE THREAD

**Issue by GordonFreemem** [bheisig/i-doit-scripts#3]
prepareIDoit writes a small php-script to get the latest i-doit version. The used php function "file_get_contents" runs in a timeout if it runs behind a proxy.

> Install i-doit pro
Identify latest version of i-doit pro
PHP Warning:  file_get_contents(https://i-doit.com/updates.xml): failed to open stream: Connection timed out in /tmp/i-doit_2017-10-16/parseupdates.php on line 3
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /tmp/i-doit_2017-10-16/parseupdates.php:3
Stack trace:
#0 /tmp/i-doit_2017-10-16/parseupdates.php(3): SimpleXMLElement->__construct('')
#1 {main}
  thrown in /tmp/i-doit_2017-10-16/parseupdates.php on line 3
Missing URL
Operation failed. Please check what is wrong and try again.

One solution would be, to read the https_proxy variable and use it to build a context, as described in https://blog.bartlweb.net/2011/04/die-php-funktion-file_get_contents-hinter-einem-proxy-server-nutzen/

Another (maybe better?) solution could be to use the already downloaded updates.xml from the preceding step:
`test ! -f "$TMP_DIR/updates.xml" && (
        "$WGET_BIN" --quiet -O "$TMP_DIR/updates.xml" "$update_file_url" || \
        abort "Unable to fetch file from '${update_file_url}'"
)`
instead of downloading it again.

Also the php-function is missing the closing `?>` before EOF on line 972.

**Comment by GordonFreemem** [comment]
Hi,

an very easy solution is to change line 970
`\$xml = new SimpleXMLElement(trim(file_get_contents('${update_file_url}')));`
to
`\$xml = new SimpleXMLElement(trim(file_get_contents('${$TMP_DIR}/updates.xml')));`

But since login.i-doit.com seems to be down at the moment I can't test it any further ;-)

**Comment by bheisig** [comment]
Hi Gordon,

Thanks again for your report. I've committed a change. The install script now asks for proxy settings. I like your suggestion to use the already downloaded file. So I changed that, too.

Btw. In PHP scripts it's recommended not to use closing tags. ;-)

Greetings,
Benjamin

**Comment by GordonFreemem** [comment]
Hi Benjamin,

for what I testet it seems to work now as expected. But as I said, since ligon.i-doit.com seemd to be down, I can't test it complete. Will continue when it's up again ;-)

> Btw. In PHP scripts it's recommended not to use closing tags. ;-)

OK, I'm not a developer. I'll take back, all I said ;-)
