### ISSUE TITLE
Not all CLI-Tools come with installation

### ISSUE THREAD

**Issue by Beckmann123** [bheisig/i-doit-scripts#5]
### Expected behavior

Expected all CLI tools to be installed.

### Actual behavior

Only idoit; idoit-backup; idoit-restore; idoit-jobs work after automatic installation of i-doit with your script.
idoit-pwd; idoit-support; idoit-hotfix are not automaticly installed (expectet this in Point 6)

### Steps to reproduce the behavior

    yes "" | ./idoit-install 

on Debian 9.9

### Thank you for your Script
Thank you for all the work you put into that scripts,
they will make i-doit easier to use for everyone!

### Screnshot:
![screen](https://user-images.githubusercontent.com/32959383/61055336-8e382200-a3f1-11e9-9907-129cf2481085.PNG)

**Comment by bheisig** [comment]
Hi,

Thanks for your report. Great to hear you find it useful.

Actually, there is a reason why the mentioned scripts are not included in the install process: They are not suitable for every supported OS but only for Debian-based distributions. We're currently working on a new [virtual appliance](https://github.com/bheisig/i-doit-appliance) which is based on Debian and will include these scripts.

If you use Debian (as you mentioned in your comment) feel free to use `idoit-pwd`, `idoit-support` and `idoit-hotfix`. I hope they are as useful as the other ones. Any feedback is appreciated.

Ben
