### ISSUE TITLE
Error in idoit-support script

### ISSUE THREAD

**Issue by Beckmann123** [bheisig/i-doit-scripts#6]
###Issue

As you can See in the Console-Log, the last call of "copyFile" there is just ohne variable set.

    function collectApplianceData {
        log "Collect information about the i-doit virtual appliance"

        copyFile "/etc/appliance_version"
    }

But the function expects two variables.

    function copyFile {
        local src="$1"
        local dest="$2"

        test -f "$src" || log "File $src does not exist"
        test -f "$src" || return

        log "Copy file $src"
        cp "$src" "$TMP_DIR/$dest"
    }

### Environment

| Question                  | Answer                            |
| ------------------------- | --------------------------------- |
| Operating system (OS)     | Debian|
| OS version                | 10 "buster"                       |

### Server logs

```bash
root@debian9:/home/jan# idoit-support
Collect data about i-doit, installed add-ons and your system
Collect hardware information
Collect OS information
Collect information about systemd units
Print systemd unit dependency graph
/usr/local/bin/idoit-support: Zeile 90: dot: Kommando nicht gefunden.
Collect installed Debian packages
Collect version information
Check services
Collect log files
Copy file /var/log/mysql/error.log
Copy file /var/log/apache2/error.log
Copy directory /var/www/html/log/
Collect PHP settings
Do you like to include /etc/php/? [Y]es [n]o: y
Copy directory /etc/php/
Collect Apache Web server settings
Do you like to include /etc/apache2/? [Y]es [n]o: y
Copy directory /etc/apache2/
Collect MariaDB settings
Do you like to include /etc/mysql/? [Y]es [n]o: y
Copy directory /etc/mysql/
Collect information about i-doit
File /var/www/html/VERSION does not exist
Copy file /var/www/html/REVISION
Do you like to include your i-doit instance? [Y]es [n]o: n
Do you like to include your i-doit databases? [Y]es [n]o: n
Collect information about the i-doit virtual appliance
/usr/local/bin/idoit-support: Zeile 208: $2 ist nicht gesetzt.
```

**Comment by bheisig** [comment]
Thanks for your report. Fixed.
